### ISSUE TITLE
Make Engine.updating protected

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/ashley#119]
Complex systems could have some special requirements on the update cycle. While the usage of engine as a "bag" for systems with listeners works perfectly, simple plain update cycle is often not enough. One example is PR #116. In other cases I would even prefer to let the user create its own update cycles which are not limited to simple iterating through the system list.

It's hard to imagine all the possibilities / needs and create the common solution. All this would be easy to implement by the user depending on the particular needs except that Engine.updating field is private. Making is protected will not influence the existing system but will allow simple creation of customized update loop by inheritance without forking / changing the source.

P.S. The same is for processPendingEntityOperations and processComponentOperations...

**Comment by monkeyhybrid** [comment]
I just commented on PR #116 to add my support for such functionality (in my case, categorising / grouping systems so I can update groups of logic and render systems individually). I think there is a real need for more flexibility and control in the update process.

**Comment by titovmaxim** [comment]
After playing with Ashley I have done my simpler version where I've completely remove Engine.update functionality. I think in real (complicated) system there will be a lot of batch processes, like update(), resize(), etc. And I found that the restriction to have only one common update() method and to control system update order makes more trouble than it solves. So I just manually call all system methods when and how I need in the correct order. Also now one system could have more than one update() method. For me it was much cleaner and convenient.

**Comment by siondream** [comment]
Ashley is meant to be a simple ECS with a clean API, I believe this would complicate things and expose more than we should. However, you are free to make the modifications you need, open source FTW.

**Comment by Nauktis** [comment]
I think this is a real issue. I understand you want to keep Ashley simple and clean but making the content of the update method (processComponentOperations and processPendingEntityOperations) protected instead of private would solve the problem without hindering Ashley and without the need to fork.

Separating the logical updates from the rendering is something many people will want. This is why Ashley, if not implementing it, should at least allow it.

@titovmaxim How did you manage to implement your own update? Does that mean your systems are not even part of the engine? How to you handle the processComponentOperations and processPendingEntityOperations?

Motivation: I am trying to update the logic and render the game asynchronously (which is a classic design). I therefor have two sets of systems, the ones that takes care of the logic and the ones that only render stuff on the screen. With the current implementation of Ashley the best I could think of is to remove from the engine all the systems related to logic when I only want to render and to remove all the systems related to rendering when I simply want to update the game... And this seems wrong :/

**Comment by titovmaxim** [comment]
@Nauktis 

After struggling with the existing design I have done my own simple system which fits my needs better. The idea is to distinguish (at least in mind :) two goals which ESC solves: multiple inheritance (Components) and batch processing (Systems). For me Components can be used separately without Systems and Systems are just a way for batch processing.

The batch processing is not only update(dt), but also something like resize, start background calculation (multithreading), render, and much more. And every batch processing operation could have several parameters, not only "dt". Hence the Systems are called manually in my case, in the desired order and with desired parameters.

The engine for me is just a pool for Entities and Components, plus a queue for pending actions, like attach/detach and destroy. The processPendingActions method of Engine is called manually (Can be just once per update, or several times depending on the case). The Engine has no idea about Systems.

Several Components are added to the Entity when it is created (obtained from the pool). At this moment every Component can ask the Entity about another Component that it needs to cooperate (either obligatory or optional). And it gets the direct references to these Components and can operate with its fields (if public) and methods. So no ComponentMapper is required at all. When the Entity is activated (added to the Engine in term of Ashley) any Component could ask the corresponding System to register it, so it will be also processed in batch manner. Therefore there is no Family concept.

Another thing I use often (which I did not found in Ashley) is an ability to use Interfaces of Components (Components). For example, a Component with 3D model could ask its Entity whether it contains another Componentg compatible with interface ITransformSource. And it then can use the methods of its interface and even register itself to RenderTransrofmSyncSystem to synchronize its transform state to the physics. It solves the same goal like get Family of several to components in Ashley, but allows more general and explicit approach.

I think this discussion is out of the Issue tracker of Ashley. You can write me PM (m.m.titov@gmail.com) if you wish.

**Comment by arapidhs** [comment]
To solve this i forked Ashley exposing Engin# update and internals. 
A common case is when you want non render systems process at fixed interval (i.e. accumulator), while render ones process continuously.

**Comment by siondream** [comment]
Why can't you use `IntervalIteratingSystem`? or `IntervalSystem`?

**Comment by arapidhs** [comment]
At the sime of forking IntervalSystem did not exist, but yes IntervalSystem it is up to the job and probably the best option now. That is, if you are not going to change the interval dynamically. 

Still, i will stick to the fork, because later in develpoment i had to make interval a Component to achieve a bullet time effect, having some systems update their interval value dynamically. But that is something totally different. 

As far as i am concernded, this could close.
