### ISSUE TITLE
ListeningSystem / how to reduce manually writing code

### ISSUE THREAD

**Issue by Lusito** [libgdx/ashley#128]
I've finished implementing ashley in my project and there are a couple of things I think could be simpler:
* There's a lot of entity iteration going on, and there are cases where I iterate multiple families in a system. In those cases, extending IteratingSystem would produce confusing code, so I implement the functionality in those systems manually (overriding addedToEngine, ...).
This is really annoying work, especially when you started just iterating one family using IteratingSystem, then added another one.
* Lots of times I find myself in need of accessing one system from another system. To do that, I need to store a reference to the engine, then ask the engine every update for the current system of the wanted class. I could store the system reference in addedToEngine, but that only works if the other system was added before this one, and would also break if the system got replaced.

So, to avoid all this manual reference updating, this is my proposal:
* interface EngineListener => void addedTo/removedFromEngine(EntitySystem system)
* interface SystemListener => void addedTo/removedFromEngine(Engine engine)
* class ListeningSystem => registers listeners
* EntityList, SortedEntityList => just like their system counterparts, except they only supply the list and implement Iterable<Entity>
* SystemInstance<T extends EntitySystem> => supplies a getter for the system

Example use of this:

    public class MySystem extends ListeningSystem {
        EntityList players = new EntityList(Family.all(PlayerComponent.class).get());
        EntityList items = new EntityList(Family.all(ItemComponent.class).get());
        SystemInstance<MyOtherSystem> otherSystem = new SystemInstance(MyOtherSystem.class);
        
        public MySystem() {
            addSystemListener(players);
            addSystemListener(items);
            addEngineListener(otherSystem);
        }
        
        @Override
        public void update(float deltaTime) {
            for(Entity entity: players) {
                handlePlayer(entity);
            }
            otherSystem.get().doStuff();
        }
    }

I'd like to know your opinion before I start on a pull request.
Good thing about this, is that it would not break existing systems, the new code could even be used to implement the existing iterating systems, to avoid code duplication and test duplication.

**Comment by siondream** [comment]
Accessing the collection of entities belong to a given family is trivial already. Imagine a `CollisionSystem` that checks for collisions between all cars and obstacles.

```java
public CollisionSystem extends EntitySystem {
	private ImmutableArray<Entity> cars;
	private ImmutableArray<Entity> obstacles;

	public CollisionSystem() {

	}

	@Override
	public void addedToEngine (Engine engine) {
		cars = engine.getEntitiesFor(Family.all(CarComponent.class, CollisionComponent.class).get());
		obstacles = engine.getEntitiesFor(Family.all(ObstacleComponent.class, CollisionComponent.class).get());
	}

	@Override
	public void update (float deltaTime) {
		for (Entity car : cars) {
			for (Entity obstacle: obstacles) {
				// ...
			}
		}
	}
}
```

Arguably this a poor design choice, because `CollisionComponent` should probably do the filtering between cars and obstacles, so we don't need to treat the entities differently, The `CollisionSystem` would only process a unique list of entities, but let's leave it like this for the sake of the discussion.

The only thing you cannot do with Ashley today is retrieving other systems from the engine. Ideally you shouldn't depend on other systems to avoid coupling but sometimes it might be hard not to.

What's stopping you from passing a reference to X system to Y system's constructor? You could also have a setter. Dependency injection is better than hardcoding the dependency. Code that uses dependency injection is a hell of a lot easier to test because you can just mock out the other system.

Unless I have missed something,  I think no changes to Ashley are needed to accommodate your use case.

**Comment by Lusito** [comment]
Nevermind, I guess I was thinking too much of a clean scenario, where every system might be replaced during runtime. That never happened in my cases, so I wrote more than was actually needed.
