### ISSUE TITLE
Refactor Engine according to single responsibility principle

### ISSUE THREAD

**Issue by saltares** [libgdx/ashley#178]
`Engine` does way too much:

* Entity management
* System management
* Signal management
* ...

Split this into smaller classes.

**Comment by Lusito** [comment]
[entityx](https://github.com/alecthomas/entityx) does this. While I do think it's nice to separate tasks, I think it's cumbersome to pass 3 manager references everywhere you need access to them. Especially since they make little sense without eachother.
If you split it up into multiple classes, it would be nice to either have proxy methods or getters for the new managers on the parent object (engine or some new context class).

**Comment by antag99** [comment]
It's a good idea to separate `Engine` into smaller classes, but they will need to communicate with each other. I don't think it's necessary to change the API; those smaller classes may be completely internal to Ashley. However, it could be a good idea to refactor Ashley for simplicity rather than dividing up the complexity... wasn't that the initial goal? IMO those delayed operations are really difficult to reason about.

**Comment by Lusito** [comment]
What would you change about the delayed operations ? I find them ugly as well, but they are needed. In ECStasy, I separated them into a different class, so I could reuse the pattern for both components and entities, but except from that I wasn't able to make it less ugly.

**Comment by saltares** [comment]
> It's a good idea to separate Engine into smaller classes, but they will need to communicate with each other

I just added this because I don't want `Engine` to become a God object. This ticket may require some research first.

**Comment by saltares** [comment]
I am doing this on the [`engine-refactor`](https://github.com/saltares/ashley/tree/engine-refactor) branch in my personal fork.

Right now, it's done so the public API remains the same and unit tests are moved/added when appropriate.

I still need to move the Family/Component stuff out of Engine and into its own class. That way Engine will stop being a God-like class.

Feel free to take a look and give feedback.

**Comment by Lusito** [comment]
any specific reason why the listener implementations are static with an engine attribute instead of just a non-static implementation without the attribute?
Aside from that there seems to be little to give feedback on yet. Waiting for the family/component stuff.

**Comment by saltares** [comment]
> any specific reason why the listener implementations are static with an engine attribute instead of just a non-static implementation without the attribute?

Will change.

> Waiting for the family/component stuff.

That's the tricky part :-).

**Comment by saltares** [comment]
I submitted a PR for people to review, let's comment on the PR itself.
