### ISSUE TITLE
Weird pool behaviour

### ISSUE THREAD

**Issue by devilbuddy** [libgdx/ashley#251]
The following small test shows something weird that i found while developing my game:

https://github.com/devilbuddy/ashley/blob/pool_problem/tests/src/com/badlogic/ashley/tests/PooledEngineTest.java

It seems something weird happening to the pooling/object construction. 

Inside my system I remove components from the system and then create new ones. But their data is not what I expect.

**Comment by mgsx-dev** [comment]
operations on entities/components during system update is delayed (not executed directly). In your test case, you expect to retrieve last added entity but since immutable arrays are not updated yet, you actually retrieve the first entity for which flag is false.

This is a documented behavior. 

My advice would be to keep track of added/removed entities inside your system. Or separate your process in 2 systems since engine is updated between 2 system updates.
