### ISSUE TITLE
Is this project still alive? Thank you.

### ISSUE THREAD

**Issue by Kiddinglife** [libgdx/ashley#292]

**Comment by dsaltares** [comment]
Hi, I am not actively maintaining it. Someone else in the libgdx contributors team could pick it up if they so desired.

**Comment by odys-z** [comment]
But why? Any technical disadvantage? LidGDX app really needs this.
I know a js version of ECS framework, and they are getting a little bit thriving after years of nobody caring. That's how opens source really is.
People can fork it. What you mean "pick it up"?

**Comment by dsaltares** [comment]
Why: because, unfortunately, I don't have the time to work on it anymore.

I mean that any of the developers who currently manage libgdx are equipped to continue work on this project if they deem it important.

Due to its open source nature anyone can fork it or work from source as well.

**Comment by odys-z** [comment]
I vote for having someone continue to work on.

**Comment by Kiddinglife** [comment]
I am hapopy maintain this repo. it seems a robust ecs impl in java world. when I saw a concept of familiy, I can say this repo was written by people who really unsersatnd and practise ecs.

**Comment by mgsx-dev** [comment]
Hi @Kiddinglife do you think it's possible to publish a new Ashley release (1.7.4) soon? Ashley 1.7.3 is no longer compatible for a while with libgdx because of GWT upgrade. Precisely [this fix](https://github.com/libgdx/ashley/pull/279). Devs have hard time with this bug.

We can discuss about it on [libgdx discord server](https://discord.gg/7c6Wg8H) if you want :-)

**Comment by odys-z** [comment]
If I understand it correctly, the problem (#279) can be fixed with uploading jar to maven central repository.
I have a maven user id but not sure if I can upload to a different artifact group id other than the group I had got by opening an maven issue.
And I think it's important been authorized by the author.

**Comment by Hronom** [comment]
Why it's closed, please can you update README.md to mention that it not actively maintained?
