### ISSUE TITLE
Complete wiki

### ISSUE THREAD

**Issue by saltares** [libgdx/ashley#35]
TODO:

- [ ] About Entity Systems
- [ ] Benchmarks
- [x] Update the demo to work with the latest changes

**Comment by JojoIce** [comment]
Just browsing through, and I got a bit confused.
https://github.com/libgdx/ashley/wiki/Built-in-Entity-Systems#intervalsystem
in the updateInterval() the code is accessing both entity and deltaTime. I think that this is wrong, since I don't think it has access to those variables. Maybe I am missing something. The example there is at least a bit confusing.

I would also like to run my gamelogic at a fixed timestep to be able to get it deterministic, and run the rendering loop as close to the native rendering interval as is possible. Any hint on that would be great in the wiki, but is maybe out of the scope for Ashley, I don't know.

**Comment by Nauktis** [comment]
@JojoIce 
I would like to comment on your last point. This is indeed a functionality that many many people will want to achieve. Many issues and even pull requests have been created already to address the fact that Ashley is too closed with systems in that regard but none have been accepted.

I managed to achieve it with some trickery. I'll provide some code when I get back home.
But I'm really convinced Ashley should be adapted so that it is possible to only update a set of systems instead of the all or nothing that is currently there.

Regards,

N.

**Comment by siondream** [comment]
@JojoIce You are right, the wiki code didn't comply with the api, it is now fixed. Thanks foe reporting.

https://github.com/libgdx/ashley/wiki/Built-in-Entity-Systems#intervalsystem

**Comment by JojoIce** [comment]
Nice, but I still think that the example code does not reflect that:

    @Override
    protected void updateInterval() {
        PositionComponent position = pm.get(entity);
        VelocityComponent velocity = vm.get(entity);

        position.x += velocity.x * interval;
        position.y += velocity.y * interval;
    }

It seems like entity is not available. I am guessing that it is best to use a quite different example, or maybe this example belongs to the IntervalIteratingSystem rather than the IntervalSystem.

**Comment by siondream** [comment]
Sorry my bad, it is now fixed.

**Comment by ploddi** [comment]
How retrieval using `ComponentMapper` is faster than `entity.getComponent` if `ComponentMapper` uses same  `entity.getComponent` method?

**Comment by JamesSkemp** [comment]
Just starting to research Ashley and ran across the empty wiki page for Entity Systems.

Is it worth just linking over to http://entity-systems.wikidot.com/ ? Or was the goal to actually have the page list out examples of both approaches?

**Comment by saltares** [comment]
I think the wiki is pretty complete now, we can close this.
